from pathlib import Path
import nbformat as nbf

nb=nbf.v4.new_notebook()
cells=[]
cells.append(nbf.v4.new_markdown_cell('''# BTC/ETH: исследование торговых стратегий\n\n**Период:** 27 сентября 2021 — 26 сентября 2026 UTC  \n**Пополнения:** $100 ежемесячно, BTC 60% / ETH 40%, всего $6,000  \n**Источник:** Binance Spot `BTCUSDT` и `ETHUSDT`, дневные OHLCV-свечи  \n\nNotebook содержит воспроизводимые таблицы, графики, проверки реализации и rolling 5-year анализ устойчивости SMA 100/150/200/250/300.'''))
cells.append(nbf.v4.new_code_cell('''from pathlib import Path\nimport json\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nfrom IPython.display import display, Markdown\n\nROOT = Path.cwd()\nRESULTS = ROOT / "results"\nDATA = ROOT / "data"\nplt.style.use("seaborn-v0_8-whitegrid")\npd.set_option("display.float_format", lambda x: f"{x:,.2f}")\nprint(f"Рабочая директория: {ROOT}")'''))
cells.append(nbf.v4.new_markdown_cell('''## Данные и контроль качества\n\nПеред использованием проверяем диапазон дат, количество свечей, дубликаты и пропуски. Прогрев индикаторов начинается 1 января 2020 года и не включается в доходность.'''))
cells.append(nbf.v4.new_code_cell('''data_checks=[]\nfor path in sorted(DATA.glob("*usdt_1d.csv")):\n    df=pd.read_csv(path, parse_dates=["open_time"])\n    gaps=(df.open_time.diff().dropna()!=pd.Timedelta(days=1)).sum()\n    data_checks.append({\n        "file":path.name, "rows":len(df), "first":df.open_time.min(),\n        "last":df.open_time.max(), "duplicates":int(df.open_time.duplicated().sum()), "gaps":int(gaps)\n    })\ndata_checks=pd.DataFrame(data_checks)\ndisplay(data_checks)\nassert (data_checks.duplicates==0).all() and (data_checks.gaps==0).all()\nprint("Проверка данных пройдена: пропусков и дубликатов нет.")'''))
cells.append(nbf.v4.new_markdown_cell('''## Итоговая таблица стратегий\n\nКомиссия — 0,10% на сторону, проскальзывание — 0,05% на сторону. Сигнал рассчитывается по закрытию завершённой свечи и исполняется по открытию следующего дня. Max DD рассчитан по time-weighted индексу, исключающему внешние пополнения.'''))
cells.append(nbf.v4.new_code_cell('''summary=pd.read_csv(RESULTS/"summary.csv")\ntotal=summary[summary.asset=="TOTAL"].copy()\ntotal["strategy"]=total.strategy.replace({\n    "DCA_REBALANCE":"DCA + monthly rebalance",\n    "DCA_SMA200_EXIT":"DCA + SMA200 exit",\n    "DCA_REBALANCE_SMA200_EXIT":"DCA + rebalance + SMA200 exit"\n})\ncols=["strategy","final_value","profit","return_pct","xirr","max_drawdown","trades","fees","slippage"]\ndisplay(total[cols].sort_values("final_value",ascending=False).style.format({\n    "final_value":"${:,.2f}","profit":"${:,.2f}","return_pct":"{:.2%}","xirr":"{:.2%}","max_drawdown":"{:.2%}","fees":"${:,.2f}","slippage":"${:,.2f}"\n}))'''))
cells.append(nbf.v4.new_markdown_cell('''### Вывод\n\nНа основном пятилетнем периоде лучшими по итоговой стоимости стали SMA 200 и эквивалентный ей вариант DCA с выходом по SMA 200. Их преимущество над обычным DCA сопровождается гораздо большим оборотом и торговыми издержками. Обычная ежемесячная ребалансировка дала лишь небольшое улучшение.'''))
cells.append(nbf.v4.new_code_cell('''strategies=["DCA","SMA200","SMA50_200","Momentum90","Donchian20_10","RSI14","Bollinger20_2","DCA_REBALANCE","DCA_SMA200_EXIT","DCA_REBALANCE_SMA200_EXIT"]\nlabels={"DCA":"DCA","SMA200":"SMA 200","SMA50_200":"SMA 50/200","Momentum90":"Momentum 90","Donchian20_10":"Donchian 20/10","RSI14":"RSI 14","Bollinger20_2":"Bollinger 20/2","DCA_REBALANCE":"DCA + rebalance","DCA_SMA200_EXIT":"DCA + SMA200 exit","DCA_REBALANCE_SMA200_EXIT":"DCA + rebalance + SMA200 exit"}\nfig,ax=plt.subplots(figsize=(14,7))\nfor s in strategies:\n    q=pd.read_csv(RESULTS/f"equity_{s}_TOTAL.csv",parse_dates=["date"])\n    ax.plot(q.date,q.equity,label=labels[s],lw=1.8)\nq=pd.read_csv(RESULTS/"equity_DCA_TOTAL.csv",parse_dates=["date"])\nax.plot(q.date,q.deposit.cumsum(),"k--",lw=1.5,label="Cumulative deposits")\nax.set_title("BTC/ETH: portfolio value")\nax.set_ylabel("USDT")\nax.legend(ncol=2,fontsize=9)\nplt.tight_layout(); plt.show()'''))
cells.append(nbf.v4.new_code_cell('''fig,ax=plt.subplots(figsize=(14,7))\nfor s in strategies:\n    q=pd.read_csv(RESULTS/f"equity_{s}_TOTAL.csv",parse_dates=["date"])\n    ax.plot(q.date,q.drawdown,label=labels[s],lw=1.5)\nax.set_title("Drawdowns adjusted for external deposits")\nax.set_ylabel("Drawdown")\nax.yaxis.set_major_formatter(lambda x,pos:f"{x:.0%}")\nax.legend(ncol=2,fontsize=9)\nplt.tight_layout(); plt.show()'''))
cells.append(nbf.v4.new_markdown_cell('''## Устойчивость длины SMA\n\nПроверены SMA 100, 150, 200, 250 и 300 на перекрывающихся пятилетних окнах с ежемесячным сдвигом даты старта. Доступный набор данных начинается 1 января 2020 года, поэтому первое полное окно начинается 27 января 2020 года; окон 2018–2019 нет.'''))
cells.append(nbf.v4.new_code_cell('''roll=pd.read_csv(RESULTS/"rolling_5y_results.csv")\nroll_summary=pd.read_csv(RESULTS/"rolling_5y_summary.csv")\ndisplay(roll_summary.style.format({"win_rate":"{:.1%}","median_difference_pct":"{:.2%}","mean_difference_pct":"{:.2%}","median_max_dd":"{:.2%}","mean_max_dd":"{:.2%}"}))\nfig,ax=plt.subplots(figsize=(12,6))\nfor w,g in roll.groupby("window"):\n    g=g.sort_values("start")\n    ax.plot(pd.to_datetime(g.start),g.difference_pct,marker="o",ms=3,label=f"SMA {w}")\nax.axhline(0,color="black",lw=1)\nax.set_title("Rolling 5-year SMA advantage over DCA")\nax.set_ylabel("Difference vs DCA")\nax.yaxis.set_major_formatter(lambda x,pos:f"{x:.0%}")\nax.legend()\nplt.tight_layout(); plt.show()'''))
cells.append(nbf.v4.new_markdown_cell('''### Вывод по rolling-тесту\n\nSMA 150 показала наиболее устойчивое поведение: она превзошла DCA в 76,2% окон, а медианная разница составила +15,33%. SMA 200 выиграла в 57,1% окон с медианной разницей +3,91%. Это не доказывает универсальность SMA 150: окна пересекаются и не являются независимыми наблюдениями, а выбор параметра по всей выборке был бы look-ahead bias.'''))
cells.append(nbf.v4.new_code_cell('''audit=pd.read_csv(RESULTS/"audit_signal_checks.csv")\ncomparison=pd.read_csv(RESULTS/"audit_trade_comparison.csv")\nprint("Покупок комбинированной стратегии вопреки собственному SMA 200:", int((~audit.buy_signal_bullish).sum()))\ndisplay(comparison[["asset","side","sma200_count","dca_sma200_count","same_signal_dates","rebalance_exit_count"]])\nprint("\\nПервые расхождения позиций:")\ndisplay(pd.read_csv(RESULTS/"audit_position_divergence.csv").groupby("asset").first())'''))
cells.append(nbf.v4.new_markdown_cell('''## Итоговые выводы и ограничения\n\n1. На периоде 27.09.2021–26.09.2026 SMA 200 увеличила итоговый портфель относительно DCA на 13,19% и снизила Max DD с 76,52% до 35,56%.\n2. Это преимущество зависит от даты старта: на периоде 2020–2025 SMA 200 уступила DCA на 6,83%.\n3. Rolling 5-year анализ показывает, что SMA 150 была устойчивее SMA 200 в доступных окнах, но результаты окон коррелированы.\n4. Данные начинаются только с 2020 года, поэтому мартовский обвал 2020 включён лишь в поздние части первого rolling-окна, а окна 2018–2019 недоступны.\n5. USDT оценивается условно как $1; модель не учитывает отклонение USDT от USD, bid/ask spread, частичные исполнения и налоги.\n\nПолный код, сырые свечи, журналы сделок, дневные equity, тесты и графики находятся в этом репозитории.'''))
nb['cells']=cells
nb['metadata']={"kernelspec":{"display_name":"Python 3 (btc_eth_backtest)","language":"python","name":"python3"},"language_info":{"name":"python","version":"3.14"}}
Path('BTC_ETH_strategy_research.ipynb').write_text(nbf.writes(nb,version=4),encoding='utf-8')
print('created BTC_ETH_strategy_research.ipynb')
